### ISSUE TITLE
usages of variable "num_snr" in create.py

### ISSUE THREAD

**Issue by backspacetg** [Sytronik/deep-griffinlim-iteration#1]
Hi! Thank you for your amazing work!
I am trying to use create.py to generate training data, but I found that no .npz file generated in the feature path after running the code.  I changed

https://github.com/Sytronik/deep-griffinlim-iteration/blob/6e6dd00e2b261bd613e5ea15fb48afdcbc0df2e9/create.py#L20

into 
```python
enumerate(range(hp.num_snr)):
```

and it worked. 

Is it reasonable to make such a change?

**Comment by Sytronik** [comment]
Oh, it's my mistake. You're right.
`for _ in range(args.num_snr):` is what I intended.

**Comment by backspacetg** [comment]
I got it! Thank you for your reply!
